#ifndef QQTBASEDLIBTEST_GLOBAL_H
#define QQTBASEDLIBTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QQTBASEDLIBTEST_LIBRARY)
#  define QQTBASEDLIBTESTSHARED_EXPORT Q_DECL_EXPORT
#elif defined (QQTBASEDLIBTEST_STATIC_LIBRARY)
#define QQTBASEDLIBTESTSHARED_EXPORT
#else
#  define QQTBASEDLIBTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QQTBASEDLIBTEST_GLOBAL_H
