#ifndef QQTDICTHELPER_H
#define QQTDICTHELPER_H

#include <qqt-local.h>

#include <qqtdictionary.h>
#include <qqtordereddictionary.h>

//别名，Q开头的Dictionary。
typedef QQtDictionary QDictionary;
typedef QQtOrderedDictionary QOrderedDictionary;

typedef QQtDictionaryMap QDictionaryMap;
typedef QQtDictionaryMapIterator QDictionaryMapIterator;
typedef QQtDictionaryMutableMapIterator QDictionaryMutableMapIterator;

typedef QQtDictionaryList QDictionaryList;
typedef QQtDictionaryListIterator QDictionaryListIterator;
typedef QQtDictionaryMutableListIterator QDictionaryMutableListIterator;

typedef QQtOrderedDictionaryMap QOrderedDictionaryMap;
typedef QQtOrderedDictionaryMapIterator QOrderedDictionaryMapIterator;
typedef QQtOrderedDictionaryMutableMapIterator QOrderedDictionaryMutableMapIterator;

typedef QQtOrderedDictionaryList QOrderedDictionaryList;
typedef QQtOrderedDictionaryListIterator QOrderedDictionaryListIterator;
typedef QQtOrderedDictionaryMutableListIterator QOrderedDictionaryMutableListIterator;

#endif // QQTDICTHELPER_H
